version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: webdb
    volumes:
      - my-data-volume:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16

volumes:
  my-data-volume: