version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: webdb
    ports:
      - 3316:3306
    volumes:
      - my-data-volume:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - 8183:80
volumes:
  my-data-volume: