version: '3.8'

services: 
    drupal:
        image: drupal
        ports:
            - "9091:80"
        volumes: 
            - drupal-www:/var/www/html
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=my-secret-pw
        volumes:
            - postgres-volume:/var/lib/postgresql/data

volumes:
    drupal-www:
    postgres-volume: